const products = [
  {
    name: 'Smartphone X1',
    category: 'Electronics',
    status: 'high',
    color: '#3498db',
    sales: 1000,
    price: 1500,
  },
  {
    name: 'Designer Jeans',
    category: 'Clothing',
    status: 'medium',
    color: '#2ecc71',
    sales: 500,
    price: 1200,
  },
  {
    name: 'Cozy Throw Blanket',
    category: 'Home Decor',
    status: 'low',
    color: '#e74c3c',
    sales: 200,
    price: 800,
  },
  {
    name: 'Wireless Headphones Pro',
    category: 'Electronics',
    status: 'medium',
    color: '#9b59b6',
    sales: 800,
    price: 1800,
  },
  {
    name: 'Running Shoes Elite',
    category: 'Footwear',
    status: 'high',
    color: '#e67e22',
    sales: 1200,
    price: 1300,
  },
  {
    name: 'Ultra HD Smart TV',
    category: 'Electronics',
    status: 'high',
    color: '#f39c12',
    sales: 1500,
    price: 2500,
  },
  {
    name: 'Gourmet Coffee Blend',
    category: 'Food & Beverages',
    status: 'low',
    color: '#1abc9c',
    sales: 300,
    price: 500,
  },
  {
    name: 'Leather Office Chair',
    category: 'Furniture',
    status: 'medium',
    color: '#c0392b',
    sales: 600,
    price: 900,
  },
  {
    name: 'Fitness Tracker Pro',
    category: 'Fitness',
    status: 'high',
    color: '#3498db',
    sales: 800,
    price: 1200,
  },
  {
    name: 'Cotton Bed Sheets Set',
    category: 'Home Decor',
    status: 'medium',
    color: '#27ae60',
    sales: 400,
    price: 700,
  },
   {
    name: "Chef's Knife Set",
    category: 'Kitchen',
    status: 'high',
    color: '#e74c3c',
    sales: 900,
    price: 1000,
  },
  {
    name: 'Adventure Backpack',
    category: 'Outdoor Gear',
    status: 'medium',
    color: '#3498db',
    sales: 700,
    price: 800,
  },
  {
    name: 'Vintage Record Player',
    category: 'Electronics',
    status: 'low',
    color: '#d35400',
    sales: 250,
    price: 1200,
  },
  {
    name: 'Organic Green Tea',
    category: 'Food & Beverages',
    status: 'medium',
    color: '#2c3e50',
    sales: 350,
    price: 300,
  },
  {
    name: 'Luxury Leather Wallet',
    category: 'Fashion Accessories',
    status: 'high',
    color: '#8e44ad',
    sales: 600,
    price: 900,
  },
  {
    name: 'HD Action Camera',
    category: 'Electronics',
    status: 'high',
    color: '#3498db',
    sales: 1100,
    price: 1800,
  },
  {
    name: 'Designer Sunglasses',
    category: 'Fashion Accessories',
    status: 'medium',
    color: '#e67e22',
    sales: 450,
    price: 700,
  },
  {
    name: 'Compact Espresso Maker',
    category: 'Kitchen',
    status: 'low',
    color: '#d35400',
    sales: 180,
    price: 1000,
  },
  {
    name: 'Durable Laptop Backpack',
    category: 'Electronics',
    status: 'medium',
    color: '#27ae60',
    sales: 550,
    price: 800,
  },
  {
    name: 'Hydration Water Bottle',
    category: 'Fitness',
    status: 'high',
    color: '#3498db',
    sales: 700,
    price: 300,
  },
];

export default products
